version: '3.8'
services:
  web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - "../.:/app"
      - bundle_cache:/usr/local/bundle
      - "../app/assets/builds:/app/app/assets/builds"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://postgres:password@db:5432/acme_widget_development

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: acme_widget_co_development


volumes:
  postgres_data:
  bundle_cache: